"""Add data profiles table

Revision ID: 059b6b8eca94
Revises: 754e10a21c41
Create Date: 2026-10-11 00:20:24.951321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '059b6b8eca94'
down_revision: Union[str, Sequence[str], None] = '754e10a21c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_profiles',
    sa.Column('data_import_id', sa.UUID(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('column_profiles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_import_id'], ['data_imports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_profiles_data_import_id'), 'data_profiles', ['data_import_id'], unique=False)
    op.create_index('ix_data_profiles_import_created', 'data_profiles', ['data_import_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_data_profiles_import_created', table_name='data_profiles')
    op.drop_index(op.f('ix_data_profiles_data_import_id'), table_name='data_profiles')
    op.drop_table('data_profiles')
    # ### end Alembic commands ###
