"""add decision_type to decisions

Revision ID: 1becf46a0faa
Revises: 76f8d7ed1ea5
Create Date: 2026-08-22 16:02:44.483421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1becf46a0faa'
down_revision: Union[str, Sequence[str], None] = '76f8d7ed1ea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('decision_type', sa.String(length=50), nullable=False))
    op.drop_column('decisions', 'descision_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('descision_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('decisions', 'decision_type')
    # ### end Alembic commands ###
