""" Added direcion to outcome metrics

Revision ID: 22ee2b7f2ef1
Revises: 3cc55dcdf92c
Create Date: 2026-10-03 16:15:22.957539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ee2b7f2ef1'
down_revision: Union[str, Sequence[str], None] = '3cc55dcdf92c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outcome_metrics', sa.Column('direction', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outcome_metrics', 'direction')
    # ### end Alembic commands ###
