"""Add data imports

Revision ID: 27deb9f1aa7a
Revises: c7d173e92a2f
Create Date: 2026-10-08 00:12:09.761320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27deb9f1aa7a'
down_revision: Union[str, Sequence[str], None] = 'c7d173e92a2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_imports',
    sa.Column('data_source_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('successful_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_imports_data_source_id'), 'data_imports', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_data_imports_status'), 'data_imports', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_imports_status'), table_name='data_imports')
    op.drop_index(op.f('ix_data_imports_data_source_id'), table_name='data_imports')
    op.drop_table('data_imports')
    # ### end Alembic commands ###
