"""Add stored file metadata to data imports

Revision ID: 280f59af2363
Revises: 27deb9f1aa7a
Create Date: 2026-10-10 22:48:16.658289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '280f59af2363'
down_revision: Union[str, Sequence[str], None] = '27deb9f1aa7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_imports', sa.Column('stored_path', sa.Text(), nullable=True))
    op.add_column('data_imports', sa.Column('file_size_bytes', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_imports', 'file_size_bytes')
    op.drop_column('data_imports', 'stored_path')
    # ### end Alembic commands ###
