"""Add outcome metrics

Revision ID: 3cc55dcdf92c
Revises: 51ca11dcf279
Create Date: 2026-10-03 00:21:02.582476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc55dcdf92c'
down_revision: Union[str, Sequence[str], None] = '51ca11dcf279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outcome_metrics',
    sa.Column('outcome_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('expected_value', sa.Numeric(), nullable=False),
    sa.Column('actual_value', sa.Numeric(), nullable=False),
    sa.Column('unit', sa.String(length=100), nullable=True),
    sa.Column('variance', sa.Numeric(), nullable=False),
    sa.Column('variance_percentage', sa.Numeric(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcomes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outcome_metrics_outcome_id'), 'outcome_metrics', ['outcome_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outcome_metrics_outcome_id'), table_name='outcome_metrics')
    op.drop_table('outcome_metrics')
    # ### end Alembic commands ###
