"""Add decision learning model

Revision ID: 4c5ddbf076d2
Revises: f266c7820038
Create Date: 2026-10-04 22:12:03.411571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c5ddbf076d2'
down_revision: Union[str, Sequence[str], None] = 'f266c7820038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_learning',
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('learning_type', sa.String(length=50), nullable=False),
    sa.Column('insight', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_learning_decision_id'), 'decision_learning', ['decision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_learning_decision_id'), table_name='decision_learning')
    op.drop_table('decision_learning')
    # ### end Alembic commands ###
