"""Added company

Revision ID: 9e8d46aabb36
Revises: 83c6cb7a8420
Create Date: 2026-07-29 21:58:27.477924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e8d46aabb36'
down_revision: Union[str, Sequence[str], None] = '83c6cb7a8420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('legal_name', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('industry_id', sa.UUID(), nullable=True))
    op.add_column('companies', sa.Column('company_size_id', sa.UUID(), nullable=True))
    op.add_column('companies', sa.Column('company_status_id', sa.UUID(), nullable=True))
    op.add_column('companies', sa.Column('country_id', sa.UUID(), nullable=True))
    op.add_column('companies', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('postal_code', sa.String(length=30), nullable=True))
    op.add_column('companies', sa.Column('address_line_1', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('address_line_2', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('employee_count', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('annual_revenue', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('companies', sa.Column('founded_year', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('companies', sa.Column('linkedin_url', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('is_customer', sa.Boolean(), nullable=False))
    op.add_column('companies', sa.Column('is_partner', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_companies_company_size_id'), 'companies', ['company_size_id'], unique=False)
    op.create_index(op.f('ix_companies_company_status_id'), 'companies', ['company_status_id'], unique=False)
    op.create_index(op.f('ix_companies_country_id'), 'companies', ['country_id'], unique=False)
    op.create_index(op.f('ix_companies_email'), 'companies', ['email'], unique=False)
    op.create_index(op.f('ix_companies_industry_id'), 'companies', ['industry_id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_organization_id'), 'companies', ['organization_id'], unique=False)
    op.create_unique_constraint('uq_company_org_name', 'companies', ['organization_id', 'name'])
    op.create_unique_constraint(None, 'companies', ['website'])
    op.drop_constraint(op.f('companies_organization_id_fkey'), 'companies', type_='foreignkey')
    op.create_foreign_key(None, 'companies', 'company_statuses', ['company_status_id'], ['id'])
    op.create_foreign_key(None, 'companies', 'countries', ['country_id'], ['id'])
    op.create_foreign_key(None, 'companies', 'industries', ['industry_id'], ['id'])
    op.create_foreign_key(None, 'companies', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'companies', 'company_sizes', ['company_size_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.create_foreign_key(op.f('companies_organization_id_fkey'), 'companies', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_constraint('uq_company_org_name', 'companies', type_='unique')
    op.drop_index(op.f('ix_companies_organization_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_industry_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_email'), table_name='companies')
    op.drop_index(op.f('ix_companies_country_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_status_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_company_size_id'), table_name='companies')
    op.drop_column('companies', 'is_partner')
    op.drop_column('companies', 'is_customer')
    op.drop_column('companies', 'linkedin_url')
    op.drop_column('companies', 'phone')
    op.drop_column('companies', 'email')
    op.drop_column('companies', 'founded_year')
    op.drop_column('companies', 'annual_revenue')
    op.drop_column('companies', 'employee_count')
    op.drop_column('companies', 'address_line_2')
    op.drop_column('companies', 'address_line_1')
    op.drop_column('companies', 'postal_code')
    op.drop_column('companies', 'state')
    op.drop_column('companies', 'city')
    op.drop_column('companies', 'country_id')
    op.drop_column('companies', 'company_status_id')
    op.drop_column('companies', 'company_size_id')
    op.drop_column('companies', 'industry_id')
    op.drop_column('companies', 'description')
    op.drop_column('companies', 'legal_name')
    # ### end Alembic commands ###
