"""Add direction to decision learning

Revision ID: b6c3995e503a
Revises: 1bbe2c99b05c
Create Date: 2026-10-05 01:00:39.203139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6c3995e503a'
down_revision: Union[str, Sequence[str], None] = '1bbe2c99b05c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decision_learning', sa.Column('direction', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decision_learning', 'direction')
    # ### end Alembic commands ###
