"""Add decision feedback model

Revision ID: f266c7820038
Revises: 22ee2b7f2ef1
Create Date: 2026-10-03 16:57:23.215518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f266c7820038'
down_revision: Union[str, Sequence[str], None] = '22ee2b7f2ef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_feedback',
    sa.Column('outcome_id', sa.UUID(), nullable=False),
    sa.Column('overall_performance', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcomes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_feedback_outcome_id'), 'decision_feedback', ['outcome_id'], unique=True)
    op.alter_column('outcome_metrics', 'direction',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outcome_metrics', 'direction',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index(op.f('ix_decision_feedback_outcome_id'), table_name='decision_feedback')
    op.drop_table('decision_feedback')
    # ### end Alembic commands ###
