from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database.models.decision.decision import Decision
from app.database.models.decision.option import DecisionOption
from app.database.models.decision.recommendation import Recommendation

from app.modules.decision.recommendation.repository import (
    RecommendationRepository,
)

from app.modules.decision.recommendation.schemas import (
    RecommendationCreate,
    RecommendationUpdate,
)
#Automation depended Libraries
from app.modules.decision.engine.service import DecisionEngineService
from app.modules.decision.engine.schemas import DecisionEvaluationRequest

from app.database.models.decision.recommendation.recommendation_history import (
    RecommendationHistory,
)
from app.modules.decision.recommendation.history_repository import (
    RecommendationHistoryRepository,
)
class RecommendationService:

    def __init__(
        self,
        repository: RecommendationRepository,
        session: AsyncSession,
    ):
        self.repository = repository
        self.session = session
        self.decision_engine_service = DecisionEngineService(session)
        self.history_repository = RecommendationHistoryRepository(session)

    async def create_recommendation(
            self,
            data: RecommendationCreate,
            organization_id:UUID,
    ) -> Recommendation:

        result = await self.session.execute(
            select(Decision).where(
                Decision.id == data.decision_id,
                Decision.organization_id == organization_id,
            )
        )

        decision = result.scalar_one_or_none()

        if decision is None:
            raise ValueError(
                "Decision not found for this organization."
            )

        result = await self.session.execute(
            select(DecisionOption).where(
                DecisionOption.id == data.recommended_option_id,
                DecisionOption.decision_id == data.decision_id,
            )
        )

        option = result.scalar_one_or_none()

        if option is None:
            raise ValueError(
                "Recommendation option does not belong to this decision"
            )

        recommendation = Recommendation(
            decision_id=data.decision_id,
            recommended_option_id=data.recommended_option_id,
            status=data.status,
            rationale=data.rationale,
            confidence=data.confidence,
            supporting_metrics=data.supporting_metrics,
            source=data.source,
        )

        return await self.repository.create(
            recommendation
        )
    async def generate_recommendation(
        self,
        decision_id: UUID,
        organization_id: UUID,
        weights: dict[str, float],
    ) -> Recommendation:

        existing_recommendation = await self.repository.get_active_by_decision(
            decision_id=decision_id,
    )

        if existing_recommendation:
            existing_recommendation.is_active = False
            await self.repository.update(existing_recommendation)

        request = DecisionEvaluationRequest(
            weights=weights
        )

        best_option = await self.decision_engine_service.evaluate_decision(
            decision_id=decision_id,
            organization_id=organization_id,
            request=request,
        )

        recommendation = Recommendation(
            decision_id=decision_id,
            recommended_option_id=best_option.option_id,
            status="PROPOSED",
            rationale=(
                "This recommendation was generated by the Decision Engine "
                "based on the configured decision metrics, their directions, "
                "and their relative weights."
            ),
            confidence=None,
            supporting_metrics={
                "decision_engine_score": best_option.score,
                "weights": weights,
            },
            source="decision_engine",
        )

        return await self.repository.create(recommendation)

    async def create_scenario_recommendation(
        self,
        decision_id: UUID,
        organization_id: UUID,
        recommended_option_id: UUID,
        score: float,
        weights: dict[str, float],
        scenario_metrics: list[dict],
    ) -> Recommendation:

        existing_recommendation = (
            await self.repository.get_active_by_decision(
                decision_id=decision_id,
            )
        )

        if existing_recommendation:
            existing_recommendation.is_active = False
            await self.repository.update(existing_recommendation)

        result = await self.session.execute(
            select(Decision).where(
                Decision.id == decision_id,
                Decision.organization_id == organization_id,
            )
        )

        decision = result.scalar_one_or_none()

        if decision is None:
            raise ValueError(
                "Decision not found for this organization."
            )

        result = await self.session.execute(
            select(DecisionOption).where(
                DecisionOption.id == recommended_option_id,
                DecisionOption.decision_id == decision_id,
            )
        )

        option = result.scalar_one_or_none()

        if option is None:
            raise ValueError(
                "Recommendation option does not belong to this decision."
            )

        recommendation = Recommendation(
            decision_id=decision_id,
            recommended_option_id=recommended_option_id,
            status="PROPOSED",
            rationale=(
                "This recommendation was generated from the evaluated "
                "scenario using the Decision Engine on scenario-adjusted "
                "metrics."
            ),
            confidence=None,
            supporting_metrics={
                "decision_engine_score": score,
                "weights": weights,
                "evaluation_type": "scenario",
                "expected_metric": scenario_metrics,
            },
            source="scenario_decision_engine",
        )

        return await self.repository.create(
            recommendation
        )

    async def get_recommendation(
        self,
        recommendation_id: UUID,
        decision_id: UUID,
        organization_id: UUID,
    ) -> Recommendation | None:

        result = await self.session.execute(
            select(Decision).where(
                Decision.id == decision_id,
                Decision.organization_id == organization_id,
            )
        )

        decision = result.scalar_one_or_none()

        if decision is None:
            return None

        return await self.repository.get_by_id(
            recommendation_id=recommendation_id,
            decision_id=decision_id,
        )

    async def list_recommendations(
        self,
        decision_id: UUID,
        organization_id: UUID,
        skip: int = 0,
        limit: int = 100,
    ) -> list[Recommendation]:

        result = await self.session.execute(
            select(Decision).where(
                Decision.id == decision_id,
                Decision.organization_id == organization_id,
            )
        )

        decision = result.scalar_one_or_none()

        if decision is None:
            return []
        

        return await self.repository.list_by_decision(
            decision_id=decision_id,
            skip=skip,
            limit=limit,
        )

    async def list_recommendation_history(
        self,
        recommendation_id: UUID,
        decision_id: UUID,
        organization_id: UUID,
    ):
        recommendation = await self.get_recommendation(
            recommendation_id=recommendation_id,
            decision_id=decision_id,
            organization_id=organization_id,
        )

        if recommendation is None:
            return None

        return await self.history_repository.list_by_recommendation(
            recommendation_id=recommendation_id,
        )
    

    

    async def update_recommendation(
        self,
        recommendation_id: UUID,
        decision_id: UUID,
        data: RecommendationUpdate,
        organization_id: UUID,
    ) -> Recommendation | None:

        recommendation = await self.get_recommendation(
            recommendation_id=recommendation_id,
            decision_id=decision_id,
            organization_id=organization_id,
        )

        if recommendation is None:
            return None

        previous_status = recommendation.status

        if data.status is not None:
            allowed_transitions = {
                "PROPOSED": {"APPROVED", "REJECTED"},
                "APPROVED": {"EXECUTED"},
                "REJECTED": set(),
                "EXECUTED": set(),
            }

            new_status = data.status

            if new_status != previous_status:
                allowed_statuses = allowed_transitions.get(
                    previous_status,
                    set(),
                )

                if new_status not in allowed_statuses:
                    raise ValueError(
                        f"Invalid recommendation status transition: "
                        f"{previous_status} -> {new_status}"
                    )
        update_data = data.model_dump(
            exclude_unset=True
        )

        for field, value in update_data.items():
            setattr(
                recommendation,
                field,
                value,
            )

        if data.status is not None and data.status != previous_status:
            history = RecommendationHistory(
                recommendation_id=recommendation.id,
                previous_status=previous_status,
                new_status=data.status,
                reason="Recommendation status updated.",
                changed_by=None,
            )

            self.session.add(history)
            await self.session.flush()

        return await self.repository.update(
            recommendation
        )

    async def delete_recommendation(
        self,
        recommendation_id: UUID,
        decision_id: UUID,
        organization_id: UUID,
    ) -> bool:

        recommendation = await self.get_recommendation(
            recommendation_id=recommendation_id,
            decision_id=decision_id,
            organization_id=organization_id,
        )

        if recommendation is None:
            return False

        await self.repository.delete(
            recommendation
        )

        return True